### ISSUE TITLE
TravisCI and Coveralls.io

### ISSUE THREAD

**Issue by bcoe** [JayBusch/beastkeeper#1]
I'm a big fan of adding TravisCI:

https://travis-ci.org/

And:

https://coveralls.io/

To projects so that folks can see the state of your unit testing/coverage (noticed you are running coverage reports and testing, might as well pipe them to a service). At the en of the day you get a slick badge that tells people you care about this sort of thing:

<img width="779" alt="screen shot 2016-03-27 at 12 36 39 pm" src="https://cloud.githubusercontent.com/assets/194609/14067363/9476e2aa-f418-11e5-963f-03a35ed886da.png">

**Comment by JayBusch** [comment]
I agree completely; however I've opted not to do this and am actually in the process of implementing something similar but not using either of those two services.  The reason being is two-fold.  

The first is that recently there have been difficulties with Travis CI builds for open-source GoLang projects because the way GoLang uses URL based package imports and that a lot of the base packages released by Google themselves are hosted at source.google.com. On systems, like TravisCI, that don't have the libraries already installed they are automatically downloaded.  TravisCI seems to do this on each and every build/test cycle, and I suspect most hosted CI solutions would as well as I'm sure they destroy the sandbox/VM/container that they use to run the unit tests after it has been run.  Well, this has resulted in google denying downloads by Travis for certain GoLang packages after free bandwidth quota's for Travis's IPs have been used up resulting in seemingly broken builds and the badges you display above going red at no fault of the project owner or developers.

Secondly, the nature of this tool and it's current state is such that it is being developed on and is only tested on FreeBSD, and uses FreeBSD specific tools (bhyve, etc.).  I plan to support OSX in a future version; but first I need to get the project to a stable and useful state so that I can use it to work on jetpack (the rkt implementation for FreeBSD).  My unit tests are likely cross platform in that they mock out the necessary objects to run without a file system; but my BDD tests are not.  They rely heavily on the ability to "do real things" to the file system and use system tools.  Thus, I would only get the unit test coverage report benefit from a hosted solution, after insuring that I in fact did properly mock everything out to be cross platform capable.

So; my solution is going to be this.  I am very close, likely as soon as the first half of this week; to being feature complete on a very early version; I believe I will call this v0.01a.  This feature set will be simply contained to what I need to move forward with jetpack.  I will at that point add code to my build scripts to use a terminal recording/gif tool that I have looked at to generate a short animated gif of my BDD tests and my Unit tests running; these as well as redirect the unit test coverage reports (HTML) will be included in the README.md or a pages.github.com site depending on how the output likes in either place.  I will then branch the repository to work on the next version, leaving the main branch for anyone who may depend on it's feature set, and attempt to maintain backwards compatibility for the bk.conf file if at all possible.  The v0.01a version will basically be capable of deploying bhyve vm's and jetpack containers to the local host; primarily to be used for jetpack testing and development.  The next versions may include cloud deployment; support for OSX; and other things as I am able to find time to complete them.

Thanks for your interest in this, and rest assured I will definitely be providing clear summaries of the coverage data; I'm just hoping to do that without creating a lot of external dependency or additional complexity because of the unique nature of the project.

**Comment by JayBusch** [comment]
I added the animation of the BDD and Unit tests today.  When they get much longer I'll split them to separate gifs.  Still need to add the detailed coverage reports but I'm itching to get to a feature complete status and bring my coverage up first.

Just FYI.
